[package]
name = "gtranslate"
version = "0.1.0"
edition = "2021"
keywords = ["google", "translations", "translator", "bindings"]
repository = ""

[dependencies]
reqwest = "0.12.12"
thiserror = "2.0.11"
tokio = { version = "1", features = ["full"] }